// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/login.ts";
import * as $4 from "./routes/api/logout.ts";
import * as $5 from "./routes/api/register.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/privacy-policy.tsx";
import * as $8 from "./routes/user/_middleware.ts";
import * as $9 from "./routes/user/dashboard.tsx";
import * as $$0 from "./islands/HomeMenu.tsx";
import * as $$1 from "./islands/LoginForm.tsx";
import * as $$2 from "./islands/PrivacySidebar.tsx";
import * as $$3 from "./islands/SignUp.tsx";
import * as $$4 from "./islands/UserSidebar.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/login.ts": $3,
    "./routes/api/logout.ts": $4,
    "./routes/api/register.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/privacy-policy.tsx": $7,
    "./routes/user/_middleware.ts": $8,
    "./routes/user/dashboard.tsx": $9,
  },
  islands: {
    "./islands/HomeMenu.tsx": $$0,
    "./islands/LoginForm.tsx": $$1,
    "./islands/PrivacySidebar.tsx": $$2,
    "./islands/SignUp.tsx": $$3,
    "./islands/UserSidebar.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
